brief: 更新录像配置
method: post
version: 2017-01-01
input:
    - name : UniqueName 
    - name : App
    - name : Pubdomain
      # must : N
    # - name : HlsVodEnable
    #   must : N
    - name : Mp4VodEnable
      must : N
      comment : 是否使能mp4, 这些参数至少带一个
    # - name : VodBucket
    #   must : N
    - name : MergeEnable
      must : N
    - name : HlsBucket
      must : N
    - name : Mp4Bucket
      must : N
    # - name : SplitFileNameM3U8
    #   must : N
    - name : LiveFileNameM3U8
      must : N
    # - name : SplitFullPathMP4
    #   must : N
    # - name : LiveFullPathMP4
    #   must : N
    # - name : SteamRecordCallbackURL
    #   must : N
    # - name : LiveRecordCallbackURL
    #   must : N
output:
